### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by moskiteau** [kaltura/server#5540] opened 2017-05-10 13:12 UTC
Hello @jessp01,

We aren't able to upload big mezzanine video files to KMC for transcoding and we get the error "Fatal transport error: Received fatal alert: handshake_failure". Here is a detailed log from our application showing the KS of the problematic upload. We've tried the upload 3 times since yesterday with similar failures. 

Now it's working, but still, this problem keeps reappearing every now and then. We keed sending tickets, but there is never a reason why or a clear fix...

```
2017-04-21 14:22:41,504 [http-bio-8080-exec-7] INFO  grails.app.services.kaltura.KalturaClientService - Generated KS locally: [MzE5ODczMzE0OWMxYjAwZTY2ZDkzNjg2NzQ4NmYyYzhkOTUxNzdmMXwyMDg1MDcxOzIwODUwNzE7MTQ5Mjg4ODk2MTsyOzI2Njc1O3Yybzs=]
2017-04-21 14:22:42,368 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - Uploading (update: false) video file: .../xyz-OVP.mp4
2017-04-21 14:22:43,013 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - HASH of fileData:1322216255
2017-04-21 14:23:13,902 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - uploaded 2% video file: 557225_221483_2112_-OVP.mp4
2017-04-21 14:23:43,417 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - uploaded 5% video file: 557225_221483_2112_-OVP.mp4
2017-04-21 14:24:11,404 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - uploaded 8% video file: 557225_221483_2112_-OVP.mp4
2017-04-21 14:24:40,024 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - uploaded 11% video file: 557225_221483_2112_-OVP.mp4
2017-04-21 14:25:08,645 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - uploaded 14% video file: 557225_221483_2112_-OVP.mp4
2017-04-21 14:25:13,774 [http-bio-8080-exec-7] ERROR com.kaltura.client.KalturaClientBase - Fatal transport error: Received fatal alert: handshake_failure

...

2017-04-21 14:25:13,796 [http-bio-8080-exec-7] ERROR kaltura.UploadToken - err: I/O exception occured while reading request response
2017-04-21 14:25:13,796 [http-bio-8080-exec-7] ERROR kaltura.UploadToken - error loading chunk!
2017-04-21 14:25:14,033 [http-bio-8080-exec-7] INFO  kaltura.UploadToken - uploaded 14% video file: 557225_221483_2112_-OVP.mp4
2017-04-21 14:25:14,033 [http-bio-8080-exec-7] WARN  kaltura.UploadToken - upload error chunk: attemptUpload - 1
2017-04-21 14:25:19,193 [http-bio-8080-exec-7] WARN  kaltura.UploadToken - upload error chunk: attemptUpload - 2
file (/tmp/xyz-OVP.mp4) is not readable or not a file
```

Thank you!

**Comment by etameran** [comment] 2017-05-10 13:21
Hi Sebastian,
What is the error you are getting when you are trying to reupload the chunk which failed?

**Comment by moskiteau** [comment] 2017-05-10 13:27
I/O exception occured while reading request response

**Comment by etameran** [comment] 2017-05-10 13:29
Can you reproduce it easily? Do you have a tcpdump recording . Did you check the http headers returned on the retry API?

**Comment by kaltura-hooks** [comment] 2017-05-10 13:32
Hi @moskiteau,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by tan-tan-kanarek** [comment] 2017-05-10 13:37
As I understand that you use the java client library, the exception stack trace can help us as well.

**Comment by moskiteau** [comment] 2017-05-10 13:37
I can't reproduce it now, as I said, it is happening now and then (3rd time now in a few month's). But when the problem happen, we can reproduce it. When we upload big files it crash after ~2gigs

We use  

https://github.com/kaltura/kaltura-chunked-upload-test/commits/master/chunkedupload/ChunkedUpload.java

**Comment by moskiteau** [comment] 2017-05-10 13:44
```
2017-05-05 16:07:14,876 [pool-26-thread-162] ERROR com.kaltura.client.KalturaClientBase - Fatal transport error: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1781)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1024)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:840)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:94)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.kaltura.client.KalturaClientBase.executeMethod(KalturaClientBase.java:309)
	at com.kaltura.client.KalturaClientBase.doQueue(KalturaClientBase.java:269)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:156)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:132)
	at kaltura.UploadToken.addChunk(UploadToken.java:227)
	at kaltura.UploadToken.uploadMediaFileAndAttachToEmptyEntry(UploadToken.java:143)
	at kaltura.UploadToken$uploadMediaFileAndAttachToEmptyEntry$0.call(Unknown Source)
	at kaltura.KalturaClientService.deliver(KalturaClientService.groovy:88)
	at kaltura.KalturaClientService$deliver.call(Unknown Source)
	at ca.onf.hook.KalturaController$_create_closure2.doCall(KalturaController.groovy:135)
```
```
2017-05-05 16:07:17,143 [pool-26-thread-162] ERROR grails.app.controllers.ca.onf.hook.KalturaController - error during kaltura transfer callback of ..._-OVP.mp4
java.lang.IllegalArgumentException: file (/tmp/556478_556215_VI58920000_-OVP.mp4) is not readable or not a file
	at com.kaltura.client.KalturaFile.<init>(KalturaFile.java:46)
	at com.kaltura.client.services.KalturaUploadTokenService.upload(KalturaUploadTokenService.java:132)
	at kaltura.UploadToken.addChunk(UploadToken.java:227)
	at kaltura.UploadToken.uploadMediaFileAndAttachToEmptyEntry(UploadToken.java:143)
```

**Comment by etameran** [comment] 2017-05-10 13:51
The sample code doesn't reset the error flag before attempting to retry the upload
Please add

errUpload = false;
before
https://github.com/kaltura/kaltura-chunked-upload-test/blob/master/chunkedupload/ChunkedUpload.java#L172

The sample code will be fixed .

**Comment by moskiteau** [comment] 2017-05-10 14:09
Cool, that's definitely a possible cause, but to be honest, it only might resolve the problem

**Comment by etameran** [comment] 2017-05-10 14:15
The reason for using chunked upload in the first place is to overcome networking problems which may cause a single chunk to fail.

**Comment by moskiteau** [comment] 2017-05-10 14:24
I agree that it is one of the reasons, but others come to mind, for example uploading files larger then 2 gigs, because kaltura didn't support it. Not using the bulk api, because frankly it sucks, ...

**Comment by jessp01** [comment] 2017-05-14 19:07
Hi @moskiteau,

Did this https://github.com/kaltura/kaltura-chunked-upload-test/commit/75ed0b13a235fec5eff121e72a828fefd278fdb9 help?

Thanks,

**Comment by moskiteau** [comment] 2017-05-17 13:51
Hello,

We'll see, when the next batch of errors happens.

Thanks

**Comment by jessp01** [comment] 2017-05-17 15:00
Hi @moskiteau,

Please open a new issue should you encounter additional problems and we'll be glad to look into it. For now, can this one be closed?

**Comment by jessp01** [comment] 2017-05-21 17:26
Closing this one as https://github.com/kaltura/kaltura-chunked-upload-test/commit/75ed0b13a235fec5eff121e72a828fefd278fdb9 appears to solve it. @moskiteau, as per my last reply, should you encounter additional problems, do let us know.

**Closed by jessp01** 2017-05-21 17:26 UTC
