### ISSUE TITLE
Internal database error in KMC.

### ISSUE THREAD

**Issue by vikchallenge** [kaltura/server#3278] opened 2015-10-06 09:46 UTC
Hello All,

While logging in KMC, I am facing issue of internal database error in analytics and dashboard.
I have created a new fresh Kaltura cluster 10.19 and I have mounted my old database to my new database.and
my mysql version is:

mysql-libs-5.1.73-5.el6_6.x86_64
mysql-5.1.73-5.el6_6.x86_64
mysql-server-5.1.73-5.el6_6.x86_64

and kaltura version is:

kaltura-base-10.19.0-10.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-x264-0.140-2.20140104.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-ffmpeg-aux-0.6-3.x86_64
kaltura-kmc-v5.39.8-2.noarch
kaltura-front-10.19.0-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-release-10.19.0-1.noarch
kaltura-monit-5.13-1.x86_64
kaltura-sphinx-2.2.1-16.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-kdp3-v3.9.9-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-librtmp-2.3-2.x86_64
kaltura-segmenter-1.0-1.x86_64
kaltura-html5-studio-v2.0.0-1.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-ffmpeg-2.1.3-9.x86_64
kaltura-widgets-1.0.0-8.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-batch-10.19.0-1.noarch
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kcw-1.0.0-6.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-html5lib-v2.34-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-nginx-1.8.0-4.x86_64
  

and while i am restarting all the kaltura services it shows : 

[root@videocms ~]# /etc/init.d/httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]
[root@videocms ~]# /etc/init.d/kaltura-monit restart
Shutting down monit:                                       [  OK  ]
Starting monit: Starting Monit 5.13 daemon with http interface at [*]:2812
                                                           [  OK  ]
[root@videocms ~]# /etc/init.d/kaltura-batch restart
Shutting down:Killing batchMgr and workers
[       OK      ]
Starting:[FAILED]
Service batch isn't running but stale lock file exists
Removing stale lock file at /opt/kaltura/log/batch/batch.pid
/usr/bin/php KGenericBatchMgr.class.php /usr/bin/php /opt/kaltura/app/configurations/batch >> /opt/kaltura/log/kaltura_batch.log 2>&1 &
[       OK      ]
[root@videocms ~]# /etc/init.d/kaltura-nginx restart
Stopping nginx:                                            [  OK  ]
Starting nginx:                                            [  OK  ]
[root@videocms ~]# /etc/init.d/kaltura-populate restart
Tue Oct 6 13:46:36 IST 2015
Shutting down:
                        Service populate isn't currently running.
Starting:
Service populate isn't running but stale lock file exists
Removing stale lock file at /opt/kaltura/log/populate.pid
/usr/bin/php populateFromLog.php >> /opt/kaltura/log/kaltura_populate.log 2>&1 &
[       OK      ]

KALTLOG OUTPUT:

2015-10-06 14:59:12 [0.000220] [122.184.129.18] [129898300] [29] [API] [KalturaFrontController->errorHandler] WARN: /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php line 1325 - mysqli_error() expects parameter 1 to be mysqli, boolean given
2015-10-06 14:59:12 [0.000179] [122.184.129.18] [129898300] [30] [API] [kCoreException->__construct] ERR: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('?SELECT??DATE(D...')
--
2015-10-06 14:59:12 [0.000191] [122.184.129.18] [129898300] [31] [API] [myReportsMgr::executeQueryByType] NOTICE: Can't use foo : 
2015-10-06 14:59:12 [0.000301] [122.184.129.18] [129898300] [32] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('?SELECT??DATE(D...')
--
2015-10-06 14:59:12 [0.000166] [122.184.129.18] [129898300] [45] [API] [KalturaFrontController->errorHandler] WARN: /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php line 1325 - mysqli_error() expects parameter 1 to be mysqli, boolean given
2015-10-06 14:59:12 [0.000169] [122.184.129.18] [129898300] [46] [API] [kCoreException->__construct] ERR: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('# return count_...')
--
2015-10-06 14:59:12 [0.000320] [122.184.129.18] [129898300] [47] [API] [myReportsMgr::executeQueryByType] NOTICE: Can't use foo : 
2015-10-06 14:59:12 [0.000177] [122.184.129.18] [129898300] [48] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('# return count_...')

![image](https://cloud.githubusercontent.com/assets/14729481/10305290/0d9d62b2-6c3d-11e5-9a1b-7ea782522448.png)

**Comment by kaltura-hooks** [comment] 2015-10-06 10:00
Hi @vikchallenge,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by vikchallenge** [comment] 2015-10-06 10:47
Hi Kalturahooks, 
we have already mentioned rpm package in above message and below
and we are using self hosted version of kaltura cluster 10.19 .

and kaltura version is:

kaltura-base-10.19.0-10.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-x264-0.140-2.20140104.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-ffmpeg-aux-0.6-3.x86_64
kaltura-kmc-v5.39.8-2.noarch
kaltura-front-10.19.0-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-release-10.19.0-1.noarch
kaltura-monit-5.13-1.x86_64
kaltura-sphinx-2.2.1-16.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-kdp3-v3.9.9-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch

my mysql version is:


mysql-libs-5.1.73-5.el6_6.x86_64
mysql-5.1.73-5.el6_6.x86_64
mysql-server-5.1.73-5.el6_6.x86_64
kaltura-kvpm-v1.0.6-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-librtmp-2.3-2.x86_64
kaltura-segmenter-1.0-1.x86_64
kaltura-html5-studio-v2.0.0-1.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-ffmpeg-2.1.3-9.x86_64
kaltura-widgets-1.0.0-8.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-batch-10.19.0-1.noarch
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kcw-1.0.0-6.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-html5lib-v2.34-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-nginx-1.8.0-4.x86_64


# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"

--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "MzEzMDM4NzJkNGFhNmRkNmJhYzQyMDkzZmYwOWZjNzUzYjgxNjFkNnwtMTs7MTQ0NjY1NjU2OTsyOzE0NDQwNjQ1NjkuMzYyMTtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:768
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4558): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'Empty reply from server' in /opt/kaltura/app/batch/client/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(817): KalturaClientBase->doQueue()
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "MDQ3NDEyNGVhMTliMDQ2MWM0MmYzZjA0N2NiNzkyMzJkMTIxNzY5NHwtMTs7MTQ0NjY1NjU1NTsyOzE0NDQwNjQ1NTUuMzg4MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:768
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(1128): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:768
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(1128): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "YWQxZjZmMjViNjdmMzQ3ZmMwZmFjNzYzZmE4NGY5MjEwODk2MTZjM3wtMTs7MTQ0NjY1NjQ2NTsyOzE0NDQwNjQ0NjUuMDU1MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:768
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaPlugins/KalturaContentDistributionClientPlugin.php(2785): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "ODIwM2ZkMjMxMTdhYmU1ZDBlMzIxM2U3NmIwMTYxMzhjNWUyNzIzNHwtMTs7MTQ0NjcwMTIxMTsyOzE0NDQxMDkyMTEuNTI0MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:768
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaPlugins/KalturaContentDistributionClientPlugin.php(2785): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "ZWM5MjRjNGY2MDllZDM5OTBkZDgwMzg2MGU0ZDQzMzMwYTg3OWUzZXwtMTs7MTQ0NjY1NjU3MDsyOzE0NDQwNjQ1NzAuMzY2ODtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:768
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4176): KalturaClientBase->throwExceptionIfError(Array)
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 768
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal database error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:768
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4176): KalturaClientBase->throwExceptionIfError(Array)

**Comment by tan-tan-kanarek** [comment] 2015-10-06 13:36
Looks like a simple login issue to mySql.
Check db configuration in /opt/kaltura/app/configurations/db.ini and reload apache to reload the configuration. To make sure it's not a granting issue in the mySql server you can temporarily change to root.

**Comment by vikchallenge** [comment] 2015-10-06 15:30
Hello tan-tan-kanarek

I think my /opt/kaltura/app/configurations/db.ini file is correct as per my details....

i am also unable to start batch service

[root@vid /]# /etc/init.d/kaltura-batch start 
Starting:[FAILED]
Service batch isn't running but stale lock file exists
Removing stale lock file at /opt/kaltura/log/batch/batch.pid
/usr/bin/php KGenericBatchMgr.class.php /usr/bin/php /opt/kaltura/app/configurations/batch >> /opt/kaltura/log/kaltura_batch.log 2>&1 &
[       OK      ]
/etc/init.d/kaltura-batch status
Service Batch isn't running


Kaltlog latest out put are --------------

#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'abc.wddemo.net..', true)
--
2015-10-06 20:44:25 [0.000000] [595848485] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'abc.wddemo.net...', true)
--
2015-10-06 20:45:35 [0.000000] [491025618] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'abc.wddemo.net...', true)
--
2015-10-06 20:46:45 [0.000000] [909239312] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'vabc.wddemo.net...', true)
--
2015-10-06 20:47:55 [0.000000] [1197780081] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'abc.wddemo.net...', true)
--
2015-10-06 20:49:06 [0.000000] [1003911051] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'abc.wddemo.net...', true)
--
2015-10-06 20:50:16 [0.000000] [892426501] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'abc.wddemo.net...', true)
--
2015-10-06 20:51:26 [0.000000] [68367844] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', abc.wddemo.net...', true)
--
2015-10-06 20:52:36 [0.000000] [112507619] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1444130679
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'abc.wddemo.net' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'abc.wddemo.net...', true)

please have a look on it.

**Comment by tan-tan-kanarek** [comment] 2015-10-06 15:45
Since your API can't access the DB and the batch can't find the configuration that matches your hostname, I would assume that your hostname is not configured well or changed after the installation and that's the cause for both issues.
You can check it by running mysql client in your cli using the same hostname and credentials as in your db.ini.
Regarding batch, you're supposed to have a section that named exactly like your machine name in batch.ini, if you find a different section name, that's probably the hostname you used during the installation.

**Comment by jessp01** [comment] 2016-01-22 12:02
Closing since no feedback was provided. If you have additional questions, please post to forum.kaltura.org as we'd rather keep the
github issue section for bug reports exclusively and the forum for general questions or ENV specific issues.

**Closed by jessp01** 2016-01-22 12:02 UTC
