### ISSUE TITLE
Login interface error

### ISSUE THREAD

**Issue by huangmeng4520** [kaltura/server#6368] opened 2017-11-20 03:00 UTC
![image](https://user-images.githubusercontent.com/8178576/33000289-1390991a-cde2-11e7-8606-3acbd1ff5a4d.png)

**Comment by kaltura-hooks** [comment] 2017-11-20 03:02
Hi @huangmeng4520,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment] 2017-12-04 13:18
Hello @huangmeng4520,

In a root shell on the server, run:
\# . /etc/profile.d/kaltura*base.sh
\# kaltlog

Then make the request and look at the log to find the error.
In parallel, also open the dev tools in your browser and look at the errors under the console and network tabs. Once you have the error, we can take from there.

Also, when prompted for the Kaltura service URL/endpoint, did you provide a hostname that is resolvable from within the Kaltura server as well as from all the hosts you intend to use it from? If not, then you should fix that by reconfiguring. See here:
https://github.com/kaltura/platform-install-packages/blob/Mercury-13.8.0/doc/kaltura-packages-faq.md#changing-apache-configurations-post-install

**Comment by jessp01** [comment] 2017-12-27 09:02
Closing due to lack of response. Please post at forum.kaltura.org if you still have an issue and provide the info I requested in my last reply.

BTW, I am able to reproduce the JQuery issue you reported and it should indeed be fixed but it's not the cause for the failure.

Thanks,

**Closed by jessp01** 2017-12-27 09:02 UTC
