### ISSUE TITLE
Access profile to block content for non-owners

### ISSUE THREAD

**Issue by abrararshad** [kaltura/server#6558] opened 2017-12-19 17:14 UTC
Trying to create a profile to block content in any context for rest of the world except the owner

I am able to create the profile using PHP and it is visible in KMC but the options that can be set using API are not available in UI and therefore cannot be verified if the profile should work or not.

After the profile is created, I assign it to a media of type image and access it via preview link. I could access it while I shouldn't be able to.

Here is the code that I came up with by exploring APIs and could be wrong...

```
$privateProfile = new \KalturaAccessControlProfile();
$privateProfile->name = 'Private';
$privateProfile->systemName = 'private';
$privateProfile->description = 'Private profile';

// Rule
$rule = new \KalturaRule();
$rule->code = '403';
$rule->message = 'Not allowed';
$rule->stopProcessing = true;

 // -> Action
$rule->actions = [\KalturaRuleActionType::BLOCK];

 // -> Condition
$authCondition = new \KalturaAuthenticatedCondition();
$authCondition->not = true;
$userEmailContextField = new \KalturaUserEmailContextField();
$authCondition->privileges = [$userEmailContextField];

$rule->conditions = [$authCondition];

// -> Contexts
$contextPlay = new \KalturaAccessControlContextTypeHolder();
$contextPlay->type = \KalturaContextType::PLAY;
$contextDownload = new \KalturaAccessControlContextTypeHolder();
 $contextDownload->type = \KalturaContextType::DOWNLOAD;

$rule->contexts = [$contextPlay, $contextDownload];

$profile = $client->accessControlProfile->add($privateProfile);

```

**Comment by kaltura-hooks** [comment] 2017-12-19 17:33
Hi @abrararshad,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by abrararshad** [comment] 2017-12-19 20:47
It was strange that I did not get any errors in the first place. I missed that line

`$privateProfile->rules = [$rule];`

Now kaltura returns "internal server error"

```
Array
(
    [code] => INTERNAL_SERVERL_ERROR
    [message] => Internal server error occurred
    [objectType] => KalturaAPIException
    [args] => Array
        (
        )
)
```
Output from `kaltlog` from kaltura server itself

```
--
            [tmp_name] => /opt/kaltura/web/tmp/phpUCy3o4
            [error] => 0
            [size] => 592082
--
            [tmp_name] => /opt/kaltura/web/tmp/phpUCy3o4
            [error] => 0
            [size] => 592082
--
    [tmp_name] => /opt/kaltura/web/tmp/phpUCy3o4
    [error] => 0
    [size] => 592082
--
    [tmp_name] => /opt/kaltura/web/tmp/phpUCy3o4
    [error] => 0
    [size] => 592082
--
]
2017-12-19 12:38:57 [0.001855] [178.153.16.112] [1975582555] [4] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'ErrorException' with message 'Argument 2 passed to KalturaRequestDeserializer::buildObject() must be of the type array, string given, called in /opt/kaltura/app/api_v3/lib/KalturaRequestDeserializer.php on line 373 and defined' in /opt/kaltura/app/api_v3/lib/KalturaRequestDeserializer.php:263
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaRequestDeserializer.php(263): KalturaFrontController->errorHandler(4096, 'Argument 2 pass...', '/opt/kaltura/ap...', 263, Array)
```

Please I need some correct references to the API here to properly create the profile

Thanks

**Comment by tan-tan-kanarek** [comment] 2017-12-21 13:56
It's hard to tell the cause for the server exception without the exact request parameters, these parameters appear in the log and could help us a lot to understand the cause.
What pops to my eyes is the fact you used KalturaRuleActionType enum in $rule->actions instead of KalturaRuleAction, that could be the cause.

Also, regarding $authCondition->privileges, you must make sure that the KS you use later to play or download the content will be populated with the exact same privilege, the user e-mail is not populated automatically by the system as KS privilege but you can add this privilege during login or KS generation.

**Comment by jessp01** [comment] 2017-12-31 20:35
Hi @abrararshad - just following up on this.. did you see @tan-tan-kanarek's reply?
Thanks,

**Comment by jessp01** [comment] 2018-01-10 23:53
Closing due to lack of response. @abrararshad - feel free to reopen should you have additional questions.

**Closed** 2018-02-13 21:51 UTC
